name: Deploy to PipeOps

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  APP_URL: https://posretail-api.pipeops.app
  APP_ENV: production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build assets
        run: npm run production

      - name: Configure environment
        run: |
          cp .env.example .env
          sed -i "s/APP_ENV=.*/APP_ENV=${{ env.APP_ENV }}/" .env
          sed -i "s/APP_URL=.*/APP_URL=${{ env.APP_URL }}/" .env

      - name: Deploy to PipeOps
        uses: pipeops/pipeops-deploy@v1
        with:
          token: ${{ secrets.PIPEOPS_TOKEN }}
          project: pos-retail
          environment: production 