name: Tida Retail Cloud Deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  LARAVEL_VERSION: 10.x
  PHP_VERSION: 8.2

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ env.PHP_VERSION }}
        extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql, bcmath, gd, redis
        coverage: none
        
    - name: Install Dependencies
      run: |
        composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
        
    - name: Copy Environment File
      run: |
        cp .env.example .env
        
    - name: Generate Application Key
      run: |
        php artisan key:generate
        
    - name: Directory Permissions
      run: |
        chmod -R 775 storage bootstrap/cache
        
    - name: Create Database
      run: |
        mysql -e 'CREATE DATABASE IF NOT EXISTS tida_retail;'
        
    - name: Execute Migrations
      run: |
        php artisan migrate --force
        
    - name: Execute Seeders
      run: |
        php artisan db:seed --force
        
    - name: Install Node Dependencies
      run: |
        npm install
        
    - name: Compile Assets
      run: |
        npm run production
        
    - name: Cache Configuration
      run: |
        php artisan config:cache
        php artisan route:cache
        php artisan view:cache
        
    - name: Setup Supervisor
      run: |
        sudo apt-get install supervisor
        sudo cp .github/supervisor/tida-retail.conf /etc/supervisor/conf.d/
        sudo supervisorctl reread
        sudo supervisorctl update
        
    - name: Setup Nginx
      run: |
        sudo apt-get install nginx
        sudo cp .github/nginx/tida-retail.conf /etc/nginx/sites-available/
        sudo ln -s /etc/nginx/sites-available/tida-retail.conf /etc/nginx/sites-enabled/
        sudo nginx -t
        sudo systemctl restart nginx
        
    - name: Setup SSL
      run: |
        sudo apt-get install certbot python3-certbot-nginx
        sudo certbot --nginx -d your-domain.com
        
    - name: Setup Redis
      run: |
        sudo apt-get install redis-server
        sudo systemctl enable redis-server
        sudo systemctl start redis-server
        
    - name: Setup Queue Worker
      run: |
        sudo cp .github/systemd/tida-retail-queue.service /etc/systemd/system/
        sudo systemctl enable tida-retail-queue
        sudo systemctl start tida-retail-queue 