version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: posretail-app
    restart: unless-stopped
    networks:
      - posretail
    volumes:
      - ./:/var/www/posretail
      - posretail-storage:/var/www/posretail/storage
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_HOST=winter-field.pleasant-way-production.svc.pipeops.internal
      - DB_PORT=3306
      - DB_DATABASE=pipeops
      - DB_USERNAME=pipeops_user
      - DB_PASSWORD=f8182a4a855070972a7f16529
      - REDIS_HOST=redis
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: posretail-redis
    restart: unless-stopped
    networks:
      - posretail

networks:
  posretail:
    driver: bridge

volumes:
  posretail-storage:
    driver: local 